spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  rabbitmq:
    ssl:
      enabled: false

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.amqp: INFO
    com.collabrium: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,beans,mappings,loggers,threaddump,heapdump

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true