services:
  postgres-users:
    image: postgres:16
    container_name: postgres-users
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  postgres-sales:
    image: postgres:16
    container_name: postgres-sales
    restart: always
    environment:
      POSTGRES_DB: sales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - sales_data:/var/lib/postgresql/data
    networks:
      - microservices-net

  users-service:
    build:
      context: ./users
      dockerfile: Dockerfile
    container_name: users-service
    depends_on:
      - postgres-users
      - discovery-server
    ports:
      - "8050:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres-users:5432/users
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    networks:
      - microservices-net

  sales-service:
    build:
      context: ./sales
      dockerfile: Dockerfile
    container_name: sales-service
    depends_on:
      - postgres-sales
      - discovery-server
    ports:
      - "8060:8080"
    environment:
      SERVER_PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres-sales:5432/sales
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    networks:
      - microservices-net

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      PORT: 8761
    networks:
      - microservices-net

  api-gateway-server:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-server
    ports:
      - "8040:8040"
    environment:
      PORT: 8040
    networks:
      - microservices-net

networks:
  microservices-net:

volumes:
  users_data:
  sales_data: