spring.application.name=api-gateway
server.port=${PORT:8040}

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Gateway Discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Routes
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=sales-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://sales-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/sales/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

# Management
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=read_only

# Logging (opcional)
logging.level.org.springframework.cloud.gateway=INFO