spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.example.ai: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.ai: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,beans,mappings,loggers,threaddump,heapdump

  endpoint:
    health:
      show-details: always

  info:
    env:
      enabled: true

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    enabled: true