apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080        # El puerto por el que accederás desde tu PC
      targetPort: 3000  # El puerto interno donde corre tu app (SERVER_PORT)