apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_PASSWORD
              value: "mi-clave-segura" # Cambia esto por tu contraseña
            - name: POSTGRES_DB   # <--- AGREGA ESTA LÍNEA
              value: "users"      # <--- AQUÍ EL NOMBRE DE TU BD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: datos-db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: datos-db
          persistentVolumeClaim:
            claimName: postgres-pvc