# =====================================
# APP
# =====================================
spring.application.name=notification-service
server.port=8070

# =====================================
# RABBITMQ
# =====================================
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# =====================================
# SENDGRID SMTP
# =====================================
spring.mail.host=${SENDGRID_HOST}
spring.mail.port=${SENDGRID_PORT}
spring.mail.username=${SENDGRID_USERNAME}
spring.mail.password=${SENDGRID_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =====================================
# EMAIL DEFAULTS
# =====================================
app.mail.from=${MAIL_FROM}

# =====================================
# ACTUATOR
# =====================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always