# =====================================
# APP
# =====================================
spring.application.name=notification-service
server.port=8070

# =====================================
# RABBITMQ
# =====================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# =====================================
# SENDGRID SMTP
# =====================================
spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =====================================
# EMAIL DEFAULTS
# =====================================
app.mail.from=miguelgomez26112001@gmail.com

# =====================================
# ACTUATOR
# =====================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always